<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>Mark Kromis</Authors>
    <Company>Mark Kromis</Company>
	  <Copyright>Copyright 2019-2024</Copyright>
	  <Description>Easy Virtual Canvas with zoom</Description>
    <PackageProjectUrl>https://github.com/TorisanKitsune/MinoriEditorShell</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TorisanKitsune/MinoriEditorShell</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <PackageTags>IDE VirtualCanvas Module</PackageTags>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <DocumentationFile>bin\MinoriEditorStudio.VirtualCanvas.xml</DocumentationFile>
	  <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
    <CodeAnalysisRuleSet>MinoriEditorShell.VirtualCanvas.Platforms.Wpf.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MinoriEditorShell.Platforms.Wpf\MinoriEditorShell.Platforms.Wpf.csproj" />
    <ProjectReference Include="..\MinoriEditorShell.VirtualCanvas\MinoriEditorShell.VirtualCanvas.csproj" />
    <ProjectReference Include="..\MinoriEditorShell\MinoriEditorShell.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Remove="C:\Users\mkrom\AppData\Roaming\SonarLint for Visual Studio\Bindings\MinoriEditorShell\csharp\SonarLint.xml" />
  </ItemGroup>
</Project>